// NLWeb endpoint for ChurnLens (Microsoft Copilot / Bing Chat)
// Auto-generated by growth engine

const content = [
  {
    "@type": "Question",
    "name": "What is SaaS churn analysis?",
    "acceptedAnswer": "SaaS churn analysis evaluates customer attrition rates, MRR impact, and retention patterns to assess business health and predict revenue risk.",
    "url": "https://churnlens.site/#faq"
  },
  {
    "@type": "Question",
    "name": "How is churn rate calculated?",
    "acceptedAnswer": "Churn rate = (customers lost in period / customers at start of period) \u00d7 100. For MRR churn, replace customers with MRR values.",
    "url": "https://churnlens.site/#faq"
  },
  {
    "@type": "Question",
    "name": "What is a good NRR for SaaS?",
    "acceptedAnswer": "NRR above 100% means expansion revenue exceeds churn. Top-tier SaaS companies target 110-130% NRR. Below 90% indicates serious retention issues.",
    "url": "https://churnlens.site/#faq"
  }
];

export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') return res.status(200).end();

  const query = req.method === 'POST'
    ? (req.body?.query || '').toLowerCase().trim()
    : (req.query.query || '').toLowerCase().trim();

  // Search FAQs
  const matches = query
    ? content.filter(c =>
        c.name.toLowerCase().includes(query) ||
        c.acceptedAnswer.toLowerCase().includes(query)
      )
    : content;

  // Only the unfiltered listing is a constant worth edge-caching; a query
  // response varies, and Vary on a query string is not a thing Vercel keys on.
  if (!query) {
    res.setHeader('Cache-Control', 'public, max-age=0, s-maxage=86400, stale-while-revalidate=604800');
  }

  return res.json({
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    'name': 'ChurnLens Knowledge Base',
    'description': 'SaaS due diligence tool. Analyze churn risk, MRR retention, and customer health for any SaaS company.',
    'numberOfItems': matches.length,
    // schema.org Question.acceptedAnswer must be an Answer node, not a bare
    // string. Emitting a string here made every item in this feed invalid for
    // the AI assistants this endpoint exists to serve.
    'itemListElement': matches.map(c => ({
      '@type': 'Question',
      'name': c.name,
      'url': c.url,
      'acceptedAnswer': { '@type': 'Answer', 'text': c.acceptedAnswer }
    }))
  });
}
