// NLWeb endpoint for ChurnLens (Microsoft Copilot / Bing Chat)
// Auto-generated by growth engine

const content = [
  {
    "@type": "Question",
    "name": "What is SaaS churn analysis?",
    "acceptedAnswer": "SaaS churn analysis evaluates customer attrition rates, MRR impact, and retention patterns to assess business health and predict revenue risk.",
    "url": "https://churnlens.site/#faq"
  },
  {
    "@type": "Question",
    "name": "How is churn rate calculated?",
    "acceptedAnswer": "Churn rate = (customers lost in period / customers at start of period) \u00d7 100. For MRR churn, replace customers with MRR values.",
    "url": "https://churnlens.site/#faq"
  },
  {
    "@type": "Question",
    "name": "What is a good NRR for SaaS?",
    "acceptedAnswer": "NRR above 100% means expansion revenue exceeds churn. Top-tier SaaS companies target 110-130% NRR. Below 90% indicates serious retention issues.",
    "url": "https://churnlens.site/#faq"
  }
];

export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  
  if (req.method === 'OPTIONS') return res.status(200).end();
  
  const query = req.method === 'POST' 
    ? (req.body?.query || '').toLowerCase()
    : (req.query.query || '').toLowerCase();
  
  // Search FAQs
  const matches = query 
    ? content.filter(c => 
        c.name.toLowerCase().includes(query) || 
        c.acceptedAnswer.toLowerCase().includes(query)
      )
    : content;
  
  return res.json({
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    'name': 'ChurnLens Knowledge Base',
    'description': 'SaaS due diligence tool. Analyze churn risk, MRR retention, and customer health for any SaaS company.',
    'numberOfItems': matches.length,
    'itemListElement': matches
  });
}
